services:
  php:
    # image: dunglas/frankenphp
    build: .
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - .:/app

  composer:
    image: composer:latest
    volumes:
      - .:/app
