version: '3'

tasks:
  default:
    cmds:
      - task --list
  silent: true

  coding-standards:apply:
    desc: "Apply coding standards"
    cmds:
      - task: coding-standards:markdown:apply
      - task: coding-standards:assets:apply

  coding-standards:check:
    desc: "Apply coding standards"
    cmds:
      - task: coding-standards:apply
      - task: coding-standards:markdown:check
      - task: coding-standards:assets:check

  coding-standards:assets:apply:
    desc: "Apply coding standards for assets"
    cmds:
      # docker: Error response from daemon: Head "https://ghcr.io/v2/biomejs/biome/manifests/1": unauthorized.
      # - docker run --rm --volume "$PWD:/workspace" ghcr.io/biomejs/biome biome check --write
      - npx @biomejs/biome check static/css --write

  coding-standards:assets:check:
    desc: "Apply and check coding standards for assets"
    cmds:
      - task: coding-standards:assets:apply
      # - docker run --rm --volume "$PWD:/workspace" ghcr.io/biomejs/biome biome check
      - npx @biomejs/biome check static/css

  coding-standards:markdown:apply:
    desc: "Apply coding standards for Markdown"
    cmds:
      - docker pull --quiet peterdavehello/markdownlint
      - docker run --rm --volume "$PWD:/md" peterdavehello/markdownlint markdownlint '**/*.md' --fix

  coding-standards:markdown:check:
    desc: "Apply and check coding standards for Markdown"
    cmds:
      - task: coding-standards:markdown:apply
      - docker pull --quiet peterdavehello/markdownlint
      - docker run --rm --volume "$PWD:/md" peterdavehello/markdownlint markdownlint '**/*.md'
